### ISSUE TITLE
just a pesky thank you issue!

### ISSUE THREAD

**Issue by hotzen** [IAreKyleW00t/docker-caddy-cloudflare#64]
request to specify donation link - thanks!

**Comment by IAreKyleW00t** [comment]
Wow, I'm flattered that you or anyone would even consider donating to a project as simple as this - Thank you so much!! I originally made this for use in my [homelab](https://github.com/IAreKyleW00t/k2net) and to give something back to the open source community. I'm just happy to see others actually making use of it! 😸 

As flattered as I am, I would ask for you to instead consider donating to the official [caddy](https://github.com/caddyserver/caddy) project as they are the ones truly making the magic happen! ✨
